[[main]]
  name = "Labs"
  pageRef = "labs"
  weight = 10

[[main]]
  name = "Friday Fun Facts"
  pageRef = "fun-facts"
  weight = 20

[[main]]
  name = "CV"
  pageRef = "cv"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40